// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Accumulator data */
export type Accu = {
  /** State of charge (%) */
  accu_state_of_charge: number;

  /** Temperature (°C) */
  accu_temperature: number;

  /** High-voltage system voltage (V) */
  hv_voltage: number;

  /** High-voltage system current (A) */
  hv_current: number;

  /** Accumulator current (A or mA depending on system) */
  current: number;

  /** Precharge relay status */
  precharge_relay: boolean;

  /** AIR+ relay status */
  air_positive: boolean;

  /** AIR- relay status */
  air_negative: boolean;
};
