// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Accumulator management system status */
export type AccuManagement = {
  /** Whether power is currently limited */
  power_limit: boolean;

  /** Instantaneous power draw (W) */
  power: number;

  /** Averaged power draw (W) */
  average_power: number;

  /** Current accumulator voltage (V) */
  voltage: number;

  /** Maximum allowed power (W) */
  max_power: number;

  /** Maximum allowed voltage (V) */
  max_voltage: number;

  /** Maximum allowed current (A) */
  max_current: number;
};
