// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "@/schemas/Time";
import { States } from "@/schemas/States";
import { Pedal } from "@/schemas/Pedal";
import { MotorController } from "@/schemas/MotorController";
import { Motor } from "@/schemas/Motor";
import { Accu } from "@/schemas/Accu";
import { AccuManagement } from "@/schemas/AccuManagement";
import { Steering } from "@/schemas/Steering";
import { Res } from "@/schemas/Res";
import { Ebs } from "@/schemas/Ebs";
import { Ros2Control } from "@/schemas/Ros2Control";
import { DriverlessSystem } from "@/schemas/DriverlessSystem";

/** Complete vehicle state */
export type Car = {
  /** ROS timestamp */
  timestamp: Time;

  /** Frame of reference */
  frame_id: string;

  /** System-wide state flags */
  states: States;

  /** Pedal sensor readings and status */
  pedal: Pedal;

  /** Motor controller status and limits */
  motor_controller: MotorController;

  /** Front-left motor data */
  motor_fl: Motor;

  /** Front-right motor data */
  motor_fr: Motor;

  /** Rear-left motor data */
  motor_rl: Motor;

  /** Rear-right motor data */
  motor_rr: Motor;

  /** Accumulator (battery) data */
  accu: Accu;

  /** Accumulator management system */
  accu_management: AccuManagement;

  /** Steering system information */
  steering: Steering;

  /** Remote emergency system */
  res: Res;

  /** Emergency braking system */
  ebs: Ebs;

  /** Control interface inputs */
  ros2control: Ros2Control;

  /** Driverless system states and flags */
  driverless_system: DriverlessSystem;

  // Future additions (not yet implemented):
  // CANOutput?: CANDataOut;
  // cockpit?: Cockpit;
  // HVVB?: HVCB;
  // ledButtonBox?: LedButtonBox;
  // pedalBox?: PedalBox;
};
