// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Drive mode setting */
export type DriveMode = {
  /** Drive mode (0 = NORMAL, 1 = SLOW, 2 = ENDURANCE) */
  mode: DriveModeEnum;
};

/** Drive mode enumeration */
export enum DriveModeEnum {
  NORMAL = 0,
  SLOW = 1,
  ENDURANCE = 2,
}
