// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Driverless system status */
export type DriverlessSystem = {
  /** Current driverless system state */
  state: DriverlessState;

  /** Emergency braking system is activated */
  ebs_activated: boolean;

  /** TS (traction system) is active */
  ts_active: boolean;

  /** A mission is selected */
  mission_selected: boolean;

  /** ASMS is on */
  asms_on: boolean;

  /** ASB checks passed */
  asb_checks_ok: boolean;

  /** Ready to drive status */
  r2d: boolean;

  /** Shutdown circuit is open at RES */
  scd_open_at_res: boolean;

  /** Mission has finished */
  mission_finished: boolean;

  /** Vehicle is at standstill */
  vehicle_at_standstill: boolean;
};

/** Driverless system states */
export enum DriverlessState {
  OFF = 0,
  READY = 1,
  DRIVING = 2,
  EMERGENCY = 3,
  FINISHED = 4,
}
