// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Emergency brake system */
export type Ebs = {
  /** Pressure in brake tank (bar) */
  pressure_tank: number;

  /** Pressure in brake system (bar) */
  pressure_system: number;
};