// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "@/schemas/Time";

/** Standard ROS header */
export type Header = {
  /** Timestamp */
  stamp: Time;

  /** Frame of reference */
  frame_id: string;
};
