// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Motor operational state */
export type MotorState = {
  /** Current motor state */
  state: MotorStateEnum;
};

/** Motor state enumeration */
export enum MotorStateEnum {
  DISABLE = 0,
  PRECHARGE = 1,
  HV_COUPLING = 2,
  READY_TO_DRIVE = 3,
  DRIVE = 4,
  RECUPERATE = 5,
  OVERHEAT = 6,
  INVERTER_ERROR_RESET = 7,
  ERROR = 8,
}
