// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { DriveMode } from "./DriveMode";
import { MotorState } from "./MotorState";

/** Motor controller status and limits */
export type MotorController = {
  /** Traction system LED status */
  ts_led: boolean;

  /** Ready-to-drive LED status */
  rtd_led: boolean;

  /** Selected drive mode */
  drive: DriveMode;

  /** Current motor state */
  motor: MotorState;

  /** Maximum allowed RPM */
  max_rpm: number;

  /** Maximum allowed torque (Nm) */
  max_torque: number;

  /** Maximum allowed motor temperature (°C) */
  max_motor_temp: number;

  /** Maximum allowed inverter temperature (°C) */
  max_inverter_temp: number;

  /** Maximum allowed IGBT temperature (°C) */
  max_igbp_temp: number;
};
