// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Pedal box status and sensor readings */
export type Pedal = {
  /** Pedal box operational state */
  pedal_box_state: PedalBoxState;

  /** Throttle left channel (max value) */
  throttle_left_max: number;

  /** Throttle left channel (min value) */
  throttle_left_min: number;

  /** Throttle left channel (current value) */
  throttle_left_value: number;

  /** Throttle right channel (max value) */
  throttle_right_max: number;

  /** Throttle right channel (min value) */
  throttle_right_min: number;

  /** Throttle right channel (current value) */
  throttle_right_value: number;

  /** Brake pressure front circuit (bar) */
  break_pressure_front: number;

  /** Brake pressure rear circuit (bar) */
  break_pressure_rear: number;

  /** Brake application percentage (0–100%) */
  break_percentage: number;

  /** Throttle application percentage (0–100%) */
  throttle_percentage: number;
};

/** Pedal box state enumeration */
export enum PedalBoxState {
  OFF = 0,
  ON = 1,
  FAILURE = 2,
  ERROR = 3,
}
