// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Header } from "@/schemas/Header";

/** Raw vehicle speed signal */
export type RawSignalVehicleSpeed = {
  /** Standard ROS header */
  header: Header;

  uint8_vehicle_speed: number;
};
