// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Header } from "@/schemas/Header";

/** Raw throttle poti command */
export type RawSignalThrottlePotiCmd = {
  /** Standard ROS header */
  header: Header;

  uint16_poti_throttle_cmd: number;
};
