// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Header } from "@/schemas/Header";

/** Raw brake signal */
export type RawSignalBrake = {
  /** Standard ROS header */
  header: Header;

  uint32_signal_brake_b: number;
  uint32_signal_brake_a: number;
};
