// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Header } from "@/schemas/Header";

/** Raw steering velocity signal */
export type RawSignalSteeringVelocity = {
  /** Standard ROS header */
  header: Header;

  int16_steering_velocity: number;
};
