// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Header } from "@/schemas/Header";

/** Raw steering velocity command */
export type RawSignalSteeringVelocityCmd = {
  /** Standard ROS header */
  header: Header;

  int16_steering_velocity_cmd: number;
};
