// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** RES (Remote Emergency System) status */
export type Res = {
  /** Emergency stop signal */
  emergency_stop: boolean;

  /** Enable signal */
  enable: boolean;

  /** Go signal */
  go_signal: boolean;

  /** Status bits from system */
  status_bit0: boolean;
  status_bit1: boolean;
  status_bit2: boolean;
  status_bit3: boolean;
  status_bit4: boolean;
  status_bit5: boolean;
  status_bit6: boolean;
  status_bit7: boolean;

  /** Signal quality (e.g. RSSI) */
  signal_quality: number;
};
