// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** ros2_control interface input */
export type Ros2Control = {
  /** Target steering angle (e.g. degrees or radians) */
  target_steering_angle: number;

  /** Target torque (Nm) */
  target_torque: number;
};
