// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Steering system state and sensor data */
export type Steering = {
  /** Motor position (e.g. encoder counts) */
  motor_position: number;

  /** Motor speed (e.g. RPM) */
  motor_speed: number;

  /** Motor current (A) */
  motor_current: number;

  /** Motor temperature (°C) */
  motor_temperature: number;

  /** Motor error code */
  motor_error: number;

  /** Steering sensor position (e.g. degrees or ticks) */
  steering_position: number;

  /** Steering speed (e.g. degrees/sec) */
  steering_speed: number;

  /** Steering trimming status */
  trimming_status: boolean;

  /** Steering failure status */
  failure_status: boolean;

  /** Steering calibration status */
  calibration_status: boolean;
};
